// Regenerates public/vendor/three-globe.mjs - a self-contained ESM bundle of three-globe with "three" rewritten to our vendored build and the unused WebGPU/TSL path stubbed out. Regenerate: npm install --no-save three-globe@^2.45 three@0.185.0 esbuild && node build.mjs

import * as esbuild from "esbuild";
import path from "path";

const OUTFILE = path.resolve("../../public/vendor/three-globe.mjs");

await esbuild.build({
	entryPoints: ["node_modules/three-globe/dist/three-globe.mjs"],
	bundle: true,
	format: "esm",
	minify: true,
	outfile: OUTFILE,
	banner: {
		js: "// Generated by tools/vendor-three-globe/build.mjs - see that file before editing this one by hand."
	},
	plugins: [
		{
			name: "single-three-instance",
			setup(build) {
				// Exact specifier "three" only, not subpaths like three/examples/jsm/... (small addons, harmless to inline).
				build.onResolve({ filter: /^three$/ }, () => ({
					path: "./three.module.min.js",
					external: true
				}));
				build.onResolve({ filter: /^three\/webgpu$/ }, () => ({
					path: path.resolve("stub-webgpu.mjs")
				}));
				build.onResolve({ filter: /^three\/tsl$/ }, () => ({
					path: path.resolve("stub-tsl.mjs")
				}));
			}
		}
	]
});

console.log("Wrote " + OUTFILE);
